
version: "3.3"
services:
  beethon:
    build:
      context: .
    image: beethon
    container_name: beethon
    restart: unless-stopped
    volumes:
      - /volshare:/volshare
    networks:
    - docker_web

volumes:
  certs:

networks:
  docker_web:
    external: true
      