# IMAGE UBUNTU
FROM ubuntu:20.04
MAINTAINER pbillerot@github.com

# ENVIRONNEMENT
ENV DEBIAN_FRONTEND="noninteractive"
ENV TZ=Europe/Paris

# TIMEZONE
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# UBUNTU PACKAGES COMPLEMENTAIRES
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    git \
    cron \
    logrotate \
    moreutils \
    nano \
    tzdata \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# ROTATION DES LOGS
ADD logrotate.conf /etc/logrotate.conf

# INSTALLATION DES EXTENSIONS PYTHON
RUN pip3 install --upgrade pip
RUN pip3 install --no-cache-dir requests matplotlib

# INSTALLATION DE PICSOU
WORKDIR /app
RUN git clone https://github.com/pbillerot/picsou.git

# INIT DU LOG FILE
RUN echo "Beenux en action..." >/var/log/beenux.log
RUN chmod 0644 /var/log/beenux.log

# PLANIFICATION DES TRAVAUX
ADD cron.crontab ./cron.crontab
RUN chmod 0644 ./cron.crontab
RUN crontab ./cron.crontab
RUN crontab -l

# POINT D'ENTREE
ADD entrypoint.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh
ENTRYPOINT ["./entrypoint.sh"]

# docker image build -t beenux:latest .
# docker run --name beenux -p 3945:3945 -d beenux:latest
# docker container ps
# docker stop beenux
# docker start beenux
