# IMAGE DEBIAN
FROM python:3.11-slim-bookworm
MAINTAINER pbillerot@github.com

# Disable Prompt During Packages Installation
# ENV DEBIAN_FRONTEND=noninteractive
# ENV DEBIAN_FRONTEND teletype

# DEBIAN CONFIG
RUN apt-get update
# - TIME ZONE Europe/Paris
RUN apt-get install -yq tzdata
RUN ln -fs /usr/share/zoneinfo/Europe/Paris /etc/localtime
RUN dpkg-reconfigure -f noninteractive tzdata

ENV TZ=Europe/Paris
# - LANG fr_FR
RUN apt-get install -y locales locales-all
ENV LC_ALL fr_FR.UTF-8
ENV LANG fr_FR.UTF-8
ENV LANGUAGE fr_FR.UTF-8

# INSTALLATION DE CRONTAB
RUN apt-get install -yq cron

# INSTALLATION DES EXTENSIONS PYTHON
RUN pip3 install --no-cache-dir requests matplotlib psycopg[binary]

WORKDIR /app

# PLANIFICATION DES TRAVAUX
ADD cron.crontab ./cron.crontab
RUN chmod 0644 ./cron.crontab
RUN crontab ./cron.crontab
RUN crontab -l

# POINT D'ENTREE
ADD entrypoint.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh
ENTRYPOINT ["./entrypoint.sh"]

# docker image build -t beethon:latest .
# docker exec --it beethon /bin/bash
# docker ps
# docker restart beethon

