
version: "3.3"
services:
  beenux:
    build:
      context: .
    image: beenux
    container_name: beenux
    restart: unless-stopped
    volumes:
      - /volshare:/volshare
      - /volshare/logs:/var/log
    networks:
    - docker_web

volumes:
  certs:

networks:
  docker_web:
    external: true
      